---
id: groonga-tokenizer-talks-naoa
base_name: groonga-tokenizer-talks-naoa
tags:
- rabbit
presentation_date: 
version: 1.0.0
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Naoya Murakami
  email: naoya@createfield.com
  rubygems_user: naoa
  slideshare_user: naoa_y
  speaker_deck_user: naoa_y
